### ISSUE TITLE
Bar Route page

### ISSUE THREAD

**Issue by LeonStechmann** [LeonStechmann/Capstone_Project_Leon#10]
### Value Proposition

As a user I need to be redirected to my current bar route page, after I submitted all necessary information (e.g. start position/address) to be able to see all the bars that are on my planned route.

### Description

![image](https://user-images.githubusercontent.com/114357032/205511568-a946d05f-2443-49a9-afec-8cd028bf4cbc.png)

### Acceptance Criteria

- [ ] after the the user submitted all required information, the user will be redirected to route page on click of submit button on home page.
- [ ] a map will show a route with all bars that were added to the route from starting position to destination (if optional destination was submitted, else the route will end on last bar)
- [ ] a list of all bars, that are on the route in chronological order of the route.
- [ ] further information for bars (e.g. time to travel to next bar, challenges for that bar etc.) will be added in later Userstory.

### Tasks

(for developers team)

- [ ] plan a route with the provided data from user (input form on homepage)
- [ ] save the data in database
- [ ] onClick of submit button change page to route page
- [ ] add component to display the list of bars on the route
- [ ] add map with route 
- [ ] add a heading with date of the route

### Sizing/Complexity

** L**
