### ISSUE TITLE
Bar list details

### ISSUE THREAD

**Issue by LeonStechmann** [LeonStechmann/Capstone_Project_Leon#11]
### Value Proposition

As a user I want the list of bars on my bar route page to provide useful information such as price range, address, image, rating to be able to get a good idea of what to expect from the bar.

### Description

Scribble / design or text

### Acceptance Criteria

- [ ] the address of the bar is provided
- [ ] the rating of the bar is provided
- [ ] the opening hours of the bar is provided
- [ ] an image of the bar is provided
- [ ] the price range of the bar is provided
- [ ] a random challenge for this stop/bar on the bar route is provided with a checkbox, that can be checked once completed.

### Tasks

(for developers team)

- [ ] add all information to the card of the bar
- [ ] add card component for each bar
- [ ] create a list of challenges
- [ ] randomize the challenge for each bar

### Sizing/Complexity

**M**
