### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by LeonStechmann** [LeonStechmann/Capstone_Project_Leon#2]
### Value Proposition
**As a user I need to to be able to navigate through my app. 

### Description

![image](https://user-images.githubusercontent.com/114357032/204253706-bd9b4e8d-260b-4aac-aa2b-134672519ab4.png)

### Acceptance Criteria

- [x] navbar is fixed on bottom of screen
- [x] the navbar should be available on all pages
- [x] three icons on navbar are clickable and lead to corresponding page (home, currentroute, previous routes)
- [x] the home icon should lead to the homepage
- [x] the route icon should lead to the current route that was planned, if no route was created yet it should be an empty page with message 'no bar route planned yet'
- [x] the list icon (right) should lead to previous routes page, should be empty if no previous routes were planned and throw message: 'no bar routes were planned in the past'

### Tasks

(for developers team)

- [x] create a new branch
- [x] create a navbar with home icon, current route icon and list icon for previous routes
- [x] create routes for all three pages from navbar icons.

### Sizing/Complexity

**S **
