### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by LeonStechmann** [LeonStechmann/Capstone_Project_Leon#3]
### Value Proposition

As a user I need a homepage with input fields to be able to create a bar route with x bars from a starting position, that is set by the me.

### Description

![image](https://user-images.githubusercontent.com/114357032/204260147-fe0e36db-a752-4b45-a7ab-dcb86dad9cf6.png)

### Acceptance Criteria

- [x] input field for starting position is required for submit
- [x] input field with destination position is optional for submit
- [x] input field with number of bars is required (capped to 7 bars for now) for submit
- [x] button to submit data and create bar route

### Tasks

(for developers team)

- [x] create input field for starting position of the bar route (required)
- [x] create input field for destination position of the bar route (optional)
- [x] create input field for number of bars on route (required, capped to 7 for now)
- [x] create submit button to submit the data of input fields and create bar route later on.
- [ ] 

### Sizing/Complexity

**S*
