### ISSUE TITLE
Autocomplete start adress input field

### ISSUE THREAD

**Issue by LeonStechmann** [LeonStechmann/Capstone_Project_Leon#6]
### Value Proposition

As a user I want to enter an address as a starting position in the corresponding input field on the homepage, which will be give autocomplete suggestions with a dropdown, to be able to set a starting point for my route.

### Description

![image](https://user-images.githubusercontent.com/114357032/204797818-619e8ec2-a562-4e85-8524-9c0a3afe2b27.png)

### Acceptance Criteria

- [ ] the address should autocomplete, thx to google autocomplete api
- [ ] The map should update and set the starting point with a marker on the map, once the user leaves focus of input field

### Tasks

(for developers team)

- [ ] implement google autocomplete
- [ ] add dropdown menu for input field with suggestions for autocompletion of the address
- [ ] make component for address start-point form 
- [ ] update map with icon on the selected starting address 

### Sizing/Complexity

** M**
