### ISSUE TITLE
Adding dynamic map to homepage

### ISSUE THREAD

**Issue by LeonStechmann** [LeonStechmann/Capstone_Project_Leon#7]
### Value Proposition

As a user I want to see a map on the homepage to be able to see where the starting point and (optionally) end point of my bar route are. 

### Description

![image](https://user-images.githubusercontent.com/114357032/204802408-c5a73bf4-6c05-4d63-9076-0f4e35179e1a.png)

### Acceptance Criteria

- [x] The default location of the map should be the geolocation / city the user is in at the moment. 
- [x] once the user adds a valid address in the input field of the starting address and leaves the focus of the input field, the map should update and set a marker on the selected starting point.

### Tasks

(for developers team)

- [x] add google maps map on homepage
- [x] make map component
- [x] add updating functionality for map

### Sizing/Complexity

**L**
