### ISSUE TITLE
Bars / Kneipen in der Nähe

### ISSUE THREAD

**Issue by LeonStechmann** [LeonStechmann/Capstone_Project_Leon#9]
### Value Proposition

As a user I want to be able to see bars that are nearby my location on the map to be able to get an idea of how many bars are close by.

### Description

![image](https://user-images.githubusercontent.com/114357032/205509233-dc8e54ef-f08a-42ee-9ee6-8cc18d344418.png)

### Acceptance Criteria

- [ ] on the rendered map, all bars close to the user are shown/marked 
- [ ] when the user pans through the map more bars in that window/ are are dynamically shown/added to the map
- [ ] only bars should be displayed on the map, no other places

### Tasks

(for developers team)

- [ ] add google cloud places search js
- [ ] search query set to only show bars on map

### Sizing/Complexity

** M **
